---
name: "gugod-perlcritic"
description: "perlcritic by gugod"
author: "Kang-min Liu <gugod@gugod.org>"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  directory:
    description: "Directory to lint"
    required: false
    default: .
  options:
    description: "Additional options"
    required: false
    default: "-p .perlcriticrc"
runs:
  using: 'docker'
  image: 'docker://gugod/perlcritic:latest'
  args:
    - "${{ inputs.options }}"
    - "${{ inputs.directory }}"
